### PR TITLE
Fixed crash caused by bluetoothLeAdvertiser NPE.

### LINKED ISSUE #84: Crashes when opening the app with turned off Bluetooth
Samsung A3 2017, Android 8

Logs: https://gist.github.com/madim/5763c2f33200b77a2187b9e86d85c63e

### PR DESCRIPTION
**Pull request by jamesjmtaylor**
https://github.com/covid19risk/covidwatch-android/issues/84
Fairly straightforward fix: ensure bluetoothLeAdvertiser isn't null before starting the service.  This occurs because the user has manually turned off bluetooth.  Thanks to https://github.com/covid19risk/covidwatch-android/issues/74 this edge case is now addressed by the UI.

### CODE REVIEW

File: app/src/main/java/org/covidwatch/android/ble/BluetoothManager.kt [hunk 1]
```diff
@@ -57,7 +58,7 @@ class BluetoothManagerImpl(
                         foregroundNotification()
                     )
                 )
-                start()
+                if (BluetoothAdapter.getDefaultAdapter().bluetoothLeAdvertiser != null) start()
```
Comment (madim) [inline app/src/main/java/org/covidwatch/android/ble/BluetoothManager.kt:61]: Seems like `bluetoothLeAdvertiser` needs both location permission, and bluetooth turned on. In my PR https://github.com/covid19risk/covidwatch-android/pull/76 I handle bluetooth, but I don't ask for location permission (I ask for location permission in the first launch of the app)

Anyway, this check fixes the crash. I'll create another PR that will ask for location permission in home screen.

**Review by madim — APPROVED** [review]
